# Generated by Django 3.0.5 on 2020-04-26 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='email',
            field=models.EmailField(default='a@a.a', max_length=255),
            preserve_default=False,
        ),
    ]
