# Generated by Django 3.0.5 on 2020-04-26 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_employee_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='okta_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
