# Generated by Django 3.0.5 on 2020-04-26 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bicycle',
            name='price',
            field=models.FloatField(default=1000),
            preserve_default=False,
        ),
    ]
